# Generated by Django 3.1.7 on 2021-03-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20210226_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='escricao_longa',
            new_name='descricao_longa',
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1),
        ),
    ]
